export const HEARTBEAT_STALE_THRESHOLD_MS = 10_000
export const HEARTBEAT_PRUNE_INTERVAL_MS = 5_000

export const SIGNAL_STRENGTH_STRONG = 0.8
export const SIGNAL_STRENGTH_MEDIUM = 0.6
export const SIGNAL_STRENGTH_WEAK = 0.4
