sonar.projectKey=mateusz-klatt_snapper-frontend
sonar.organization=mateusz-klatt

sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=dist/**,node_modules/**,coverage/**,build/**,public/icons/**,**/*.generated.*,scripts/**
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,*.config.ts,*.config.js,**/*.generated.*,vite.config.ts,vitest.config.ts
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.environments=browser,node

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
