export type { Components, Operations, Paths } from './api.generated'
import type { Components } from './api.generated'

export type CandleData = Components['schemas']['CandleData']
export type OrderData = Components['schemas']['OrderData']
export type ExecutionData = Components['schemas']['ExecutionData']
export type SignalData = Components['schemas']['SignalData']
export type PositionData = Components['schemas']['PositionData']
export type UserProfile = Components['schemas']['UserProfile']
export type UserResponse = Components['schemas']['UserResponse']
export type UserListResponse = Components['schemas']['UserListResponse']
export type DelegateRead = Components['schemas']['DelegateRead']
export type DelegateListResponse = Components['schemas']['DelegateListResponse']
export type DelegateResponse = Components['schemas']['DelegateResponse']
export type DelegateCreatedPayload = Components['schemas']['DelegateCreatedPayload']
export type DelegateCreatedResponse = Components['schemas']['DelegateCreatedResponse']
export type SettingRead = Components['schemas']['SettingRead']
export type SettingUpdate = Components['schemas']['SettingUpdate']
export type SettingUpdateBody = Components['schemas']['SettingUpdateBody']
export type SettingResponse = Components['schemas']['SettingResponse']
export type SettingListResponse = Components['schemas']['SettingListResponse']
export type ExchangeListResponse = Components['schemas']['ExchangeListResponse']
export type InstrumentListResponse = Components['schemas']['InstrumentListResponse']
export type InstrumentDetailData = Components['schemas']['InstrumentDetailData']
export type InstrumentDetailListResponse = Components['schemas']['InstrumentDetailListResponse']
export type RelatedInstrumentData = Components['schemas']['RelatedInstrumentData']
export type RelatedInstrumentsGroup = Components['schemas']['RelatedInstrumentsGroup']
export type RelatedInstrumentsPayloadData = Components['schemas']['RelatedInstrumentsPayloadData']
export type RelatedInstrumentsResponse = Components['schemas']['RelatedInstrumentsResponse']
export type RelatedInstrumentsSelected = Components['schemas']['RelatedInstrumentsSelected']
export type RelatedInstrumentsUnderlying = Components['schemas']['RelatedInstrumentsUnderlying']
export type UnderlyingAssetData = Components['schemas']['UnderlyingAssetData']
export type UnderlyingAssetListResponse = Components['schemas']['UnderlyingAssetListResponse']
export type AdminAiReviewItem = Components['schemas']['AdminAiReviewItem']
export type AdminAiReviewListResponse = Components['schemas']['AdminAiReviewListResponse']
export type CachedCandle = Components['schemas']['CachedCandle']
export type CachedCandlesPayload = Components['schemas']['CachedCandlesPayload']
export type CachedCandlesResponse = Components['schemas']['CachedCandlesResponse']
export type CachedStatsPayload = Components['schemas']['CachedStatsPayload']
export type CachedStatsResponse = Components['schemas']['CachedStatsResponse']
export type ListedCachedStatsPayload = Components['schemas']['ListedCachedStatsPayload']
export type ListedCachedStatsResponse = Components['schemas']['ListedCachedStatsResponse']
export type CacheHealthPayload = Components['schemas']['CacheHealthPayload']
export type CacheHealthResponse = Components['schemas']['CacheHealthResponse']
export type OperatorInfo = Components['schemas']['OperatorInfo']
export type OperatorListResponse = Components['schemas']['OperatorListResponse']
export type OperatorResponse = Components['schemas']['OperatorResponse']
export type CreateOperatorBody = Components['schemas']['CreateOperatorBody']
export type WalletInfo = Components['schemas']['WalletInfo']
export type WalletListResponse = Components['schemas']['WalletListResponse']
export type ScopeGrantInfo = Components['schemas']['ScopeGrantInfo']
export type ScopeGrantListResponse = Components['schemas']['ScopeGrantListResponse']
export type ScopeGrantResponse = Components['schemas']['ScopeGrantResponse']
export type CreateScopeGrantBody = Components['schemas']['CreateScopeGrantBody']
export type HandoverScopeGrantBody = Components['schemas']['HandoverScopeGrantBody']
export type HandoverScopeGrantResponse = Components['schemas']['HandoverScopeGrantResponse']
export type CredentialSummary = Components['schemas']['CredentialSummary']
export type CredentialListResponse = Components['schemas']['CredentialListResponse']
export type CredentialResponse = Components['schemas']['CredentialResponse']
export type CreateCredentialBody = Components['schemas']['CreateCredentialBody']
export type RotateCredentialBody = Components['schemas']['RotateCredentialBody']
export type SetCredentialReconciliationMethodBody =
  Components['schemas']['SetCredentialReconciliationMethodBody']
export type CredentialReconciliationMethodResponse =
  Components['schemas']['CredentialReconciliationMethodResponse']
export type RealPortfolioReconciliationMethod =
  Components['schemas']['RealPortfolioReconciliationMethod']
export type OrderListResponse = Components['schemas']['OrderListResponse']
export type ExecutionListResponse = Components['schemas']['ExecutionListResponse']
export type PositionListResponse = Components['schemas']['PositionListResponse']
export type AccountBalanceEntry = Components['schemas']['AccountBalanceEntry']
export type AccountPositionEntry = Components['schemas']['AccountPositionEntry']
export type PortfolioAccountState = Components['schemas']['PortfolioAccountState']
export type PortfolioAccountStateListResponse =
  Components['schemas']['PortfolioAccountStateListResponse']
export type PnlInstrumentContributionData = Components['schemas']['PnlInstrumentContributionData']
export type PnlSeriesData = Components['schemas']['PnlSeriesData']
export type PnlSeriesResponse = Components['schemas']['PnlSeriesResponse']
export type PnlTimelinePointData = Components['schemas']['PnlTimelinePointData']
export type PnlTimelineData = Components['schemas']['PnlTimelineData']
export type PnlTimelineResponse = Components['schemas']['PnlTimelineResponse']
export type PnlTimelineMarkerData = PnlTimelineData['markers'][number]
export type PnlValuationStatus = Components['schemas']['PnlValuationStatus']
export type PortfolioPnlGranularity = '1m' | '5m' | '1h' | '1d'
export type SignalListResponse = Components['schemas']['SignalListResponse']
export type AlertEventInfo = Components['schemas']['AlertEventInfo']
export type AlertEventResponse = Components['schemas']['AlertEventResponse']
export type AlertHistoryResponse = Components['schemas']['AlertHistoryResponse']
export type UserRole = Components['schemas']['UserRole']
export type LoginRequest = Components['schemas']['LoginRequest']
export type LoginBody = Components['schemas']['LoginBody']
export type CreateUserRequest = Components['schemas']['CreateUserRequest']
export type CreateUserBody = Components['schemas']['CreateUserBody']
export type UpdateUserRequest = Components['schemas']['UpdateUserRequest']
export type UpdateUserBody = Components['schemas']['UpdateUserBody']
export type ChangePasswordRequest = Components['schemas']['ChangePasswordRequest']
export type ChangePasswordBody = Components['schemas']['ChangePasswordBody']
export type AdminResetPasswordRequest = Components['schemas']['AdminResetPasswordRequest']
export type AdminResetPasswordBody = Components['schemas']['AdminResetPasswordBody']
export type ValidationError = Components['schemas']['ValidationError']
export type HTTPValidationError = Components['schemas']['HTTPValidationError']
export type ConfiguredProcess = Components['schemas']['ConfiguredProcess']
export type ConfiguredProcessesResponse = Components['schemas']['ConfiguredProcessesResponse']
export type AvailableProcess = Components['schemas']['AvailableProcess']
export type AvailableProcessesResponse = Components['schemas']['AvailableProcessesResponse']
export type ProcessRun = Components['schemas']['ProcessRun']
export type ProcessRunsResponse = Components['schemas']['ProcessRunsResponse']
export type ProcessSchemaData = Components['schemas']['ProcessSchemaData']
export type ProcessSchemaResponse = Components['schemas']['ProcessSchemaResponse']
export type ProcessCreatedInfo = Components['schemas']['ProcessCreatedInfo']
export type ProcessCreateResponse = Components['schemas']['ProcessCreateResponse']
export type ProcessCreateBody = Components['schemas']['ProcessCreateBody']
export type ProcessCreateRequest = Components['schemas']['ProcessCreateRequest']
export type ProcessStartBody = Components['schemas']['ProcessStartBody']
export type ProcessStartRequest = Components['schemas']['ProcessStartRequest']
export type ProcessStartResponse = Components['schemas']['ProcessStartResponse']
export type ProcessStopResponse = Components['schemas']['ProcessStopResponse']
export type ProcessDesiredStateBody = Components['schemas']['ProcessDesiredStateBody']
export type ProcessDesiredStateResponse = Components['schemas']['ProcessDesiredStateResponse']
export type ProcessConfigScopeBody = Components['schemas']['ProcessConfigScopeBody']
export type ProcessConfigScopeResponse = Components['schemas']['ProcessConfigScopeResponse']
export type ProcessCategoryCount = Components['schemas']['ProcessCategoryCount']
export type ProcessSummaryResponse = Components['schemas']['ProcessSummaryResponse']
export type ProcessSummaryData = Components['schemas']['ProcessSummaryData']
export type StrategyProcess = Components['schemas']['StrategyProcess']
export type StrategyListResponse = Components['schemas']['StrategyListResponse']
export type ProcessStatus = Components['schemas']['ProcessStatus']
export type SystemStatusResponse = Components['schemas']['SystemStatusResponse']
export type HealthCheckResponse = Components['schemas']['HealthCheckResponse']
export type MessageResponse = Components['schemas']['MessageResponse']
export type ExecutionPlanData = Components['schemas']['ExecutionPlanData']
export type ExecutionPlanResponse = Components['schemas']['ExecutionPlanResponse']
export type BracketCreateBody = Components['schemas']['BracketCreateBody']
export type BracketCancelBody = Components['schemas']['BracketCancelBody']
export type TrailingStopCreateBody = Components['schemas']['TrailingStopCreateBody']
export type TrailingStopCancelBody = Components['schemas']['TrailingStopCancelBody']
export type TrailingStopStateData = Components['schemas']['TrailingStopStateData']
export type TrailingStopStateResponse = Components['schemas']['TrailingStopStateResponse']

export type TrailingStopByCycleResult = TrailingStopStateResponse | MessageResponse

export type BacktestRunData = Components['schemas']['BacktestRunData']
export type BacktestRunDetailData = Components['schemas']['BacktestRunDetailData']
export type BacktestRunResponse = Components['schemas']['BacktestRunResponse']
export type BacktestRunDetailResponse = Components['schemas']['BacktestRunDetailResponse']
export type BacktestRunListResponse = Components['schemas']['BacktestRunListResponse']
export type BacktestStrategyClassListResponse =
  Components['schemas']['BacktestStrategyClassListResponse']
export type BacktestTradeData = Components['schemas']['BacktestTradeData']
export type BacktestTradeListResponse = Components['schemas']['BacktestTradeListResponse']
export type BacktestSignalData = Components['schemas']['BacktestSignalData']
export type BacktestSignalListResponse = Components['schemas']['BacktestSignalListResponse']
export type BacktestEventData = Components['schemas']['BacktestEventData']
export type BacktestEventListResponse = Components['schemas']['BacktestEventListResponse']
export type BacktestCreateBody = Components['schemas']['BacktestCreateBody']
export type BacktestCancelBody = Components['schemas']['BacktestCancelBody']
export type BacktestCompareBody = Components['schemas']['BacktestCompareBody']
export type BacktestComparisonData = Components['schemas']['BacktestComparisonData']
export type BacktestComparisonResponse = Components['schemas']['BacktestComparisonResponse']
export type BacktestComparisonDetailResponse =
  Components['schemas']['BacktestComparisonDetailResponse']
export type BacktestComparisonDetailResponseData =
  Components['schemas']['BacktestComparisonDetailResponseData']
export type BacktestComparisonListResponse = Components['schemas']['BacktestComparisonListResponse']
export type MetricDiffRow = Components['schemas']['MetricDiffRow']
export type EquityOverlayPoint = Components['schemas']['EquityOverlayPoint']
export type TradeDiffEntry = Components['schemas']['TradeDiffEntry']
export type SignalDiffEntry = Components['schemas']['SignalDiffEntry']

export type FeatureFlagsResponse = Components['schemas']['FeatureFlagsResponse']
export type DelegateCreateBody = Components['schemas']['DelegateCreateBody']
export type DelegateCapsBody = Components['schemas']['DelegateCapsBody']
export type DelegateCapsUpdateBody = Components['schemas']['DelegateCapsUpdateBody']

export type SystemMetricsResponse = Components['schemas']['SystemMetricsResponse']
export type SystemMetricsData = Components['schemas']['SystemMetricsData']

export type DbStatsResponse = Components['schemas']['DbStatsResponse']
export type DbStatsData = Components['schemas']['DbStatsData']
export type TableStatsItem = Components['schemas']['TableStatsItem']

export type NotificationMetricsResponse = Components['schemas']['NotificationMetricsResponse']
export type NotificationMetricsData = Components['schemas']['NotificationMetricsData']

export type RetentionRunResponse = Components['schemas']['RetentionRunResponse']
export type RetentionRunData = Components['schemas']['RetentionRunData']
export type RetentionPolicyResult = Components['schemas']['RetentionPolicyResult']

export type EgressActiveReservationSnapshot =
  Components['schemas']['EgressActiveReservationSnapshot']
export type EgressConnectionSnapshot = Components['schemas']['EgressConnectionSnapshot']
export type EgressContainerSummary = Components['schemas']['EgressContainerSummary']
export type EgressHealthResponse = Components['schemas']['EgressHealthResponse']
export type EgressHealthData = Components['schemas']['EgressHealthData']
export type EgressRouteStatusSnapshot = Components['schemas']['EgressRouteStatusSnapshot']
