/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebSocketMessages =
  | StrictDataSchema
  | AiReviewCapsViolationFrameData
  | AiReviewDecisionAckFrameData
  | AiReviewDecisionData
  | AiReviewRequestFrameData
  | AlertEventData
  | BacktestProgressData
  | CandleData
  | CapsViolationAfterAiApproveData
  | ContinuousCandleData
  | ContractData
  | DelegateOfflineData
  | ExecutionData
  | ExecutionPlanData
  | ExecutionPlanDecisionEventData
  | FrontMonthData
  | FundingAccrualData
  | HeartbeatData
  | InstrumentCapabilityData
  | InstrumentDetailData
  | OrderCancelData
  | OrderData
  | OrderEventData
  | OrderReplaceData
  | OrderRequestData
  | PositionData
  | ReplayEndData
  | ReplayStartData
  | ScopeRevokedData
  | SettingChangedData
  | SignalData
  | SymbolAliasUpdateData
  | TickData
  | TradeData
  | UnderlyingAssetData
  | UnderlyingInstrumentData
  | UserDeactivatedData
  | VenueFeeScheduleData
  | WSAuthCompleteResponse
  | WSAuthExpiredResponse
  | WSAuthFailedResponse
  | WSAuthOkResponse
  | WSAuthRequiredResponse
  | WSAuthenticateRequest
  | WSErrorResponse
  | WSGetSubscriptionsRequest
  | WSPingRequest
  | WSPongResponse
  | WSReauthOkResponse
  | WSReauthRequest
  | WSReauthRequiredResponse
  | WSSubscribeRequest
  | WSSubscriptionSuccessResponse
  | WSSubscriptionsListResponse
  | WSUnsubscribeRequest;
export type Topic = string | null;
export type Type = "ai_review.caps_violation";
export type Topic1 = string | null;
export type Type1 = "ai_review.decision_ack";
export type Topic2 = string | null;
export type Rationale = string | null;
export type Type2 = "ai_review_decision";
export type Topic3 = string | null;
export type Type3 = "ai_review.request";
export type Topic4 = string | null;
export type JsonValue =
  | JsonPrimitive
  | JsonValue[]
  | {
      [k: string]: JsonValue;
    };
export type JsonPrimitive = string | number | boolean | null;
export type Type4 = "alert_event";
export type Topic5 = string | null;
export type OperatorPublicId = string | null;
export type WalletPublicId = string | null;
export type AlertType =
  | "order_fill_full"
  | "order_rejected"
  | "position_stop_loss_fired"
  | "margin_warning"
  | "critical_system_error";
export type Priority = "low" | "medium" | "high";
export type DedupKey = string | null;
export type ThreadKey = string | null;
export type SourceTopic = string | null;
export type Type5 = "backtest_progress";
export type Topic6 = string | null;
export type Event = "started" | "progress" | "milestone" | "completed" | "failed" | "cancelled";
export type Milestone = ("25pct" | "50pct" | "75pct") | null;
export type TotalCandles = number | null;
export type Type6 = "candle";
export type Topic7 = string | null;
export type Exchange = "kraken" | "kraken_futures" | "kraken_equities" | "walutomat" | "polygon";
export type Vwap = number | null;
export type Trades = number | null;
export type Type7 = "caps_violation_after_ai_approve";
export type Topic8 = string | null;
export type Type8 = "continuous_candle";
export type Topic9 = string | null;
export type Vwap1 = number | null;
export type Trades1 = number | null;
export type AdjustmentFactor = number | null;
export type Type9 = "contract";
export type Topic10 = string | null;
export type ExpiryAt = string | null;
export type InstrumentKind = string | null;
export type ContractFamily = string | null;
export type Type10 = "delegate_offline";
export type Topic11 = string | null;
export type Type11 = "execution";
export type Topic12 = string | null;
export type TradeId = string | null;
export type ExchangeOrderId = string | null;
export type Exchange1 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Side = "buy" | "sell";
export type Status = "filled" | "partial";
export type OperatorPublicId1 = string | null;
export type UserPublicId = string | null;
export type Type12 = "execution_plan";
export type Topic13 = string | null;
export type OperatorPublicId2 = string | null;
export type PositionCyclePublicId = string | null;
export type ParentPlanPublicId = string | null;
export type LastError = string | null;
export type IdempotencyKey = string | null;
export type Type13 = "execution_plan_decision_event";
export type Topic14 = string | null;
export type Type14 = "front_month";
export type Topic15 = string | null;
export type ContractFamily1 = string | null;
export type Type15 = "funding_accrual";
export type Topic16 = string | null;
export type Exchange2 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode = "live" | "paper";
export type AccrualType = "funding" | "rollover" | "borrow";
export type Type16 = "heartbeat";
export type Topic17 = string | null;
export type Status1 = "healthy" | "warning" | "error";
export type Type17 = "instrument_capability";
export type Topic18 = string | null;
export type SupportedOrderTypes = string[];
export type MinNotional = number | null;
export type MaxOrderSize = number | null;
export type Type18 = "instrument_detail";
export type Topic19 = string | null;
export type InstrumentKind1 = string | null;
export type ExpiryAt1 = string | null;
export type Type19 = "order_cancel";
export type Topic20 = string | null;
export type Exchange3 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type OperatorPublicId3 = string | null;
export type UserPublicId1 = string | null;
export type Type20 = "order";
export type Topic21 = string | null;
export type ExchangeOrderId1 = string | null;
export type Exchange4 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode1 = "live" | "paper";
export type Side1 = "buy" | "sell";
export type OrderType = "market" | "limit" | "stop" | "stop_limit";
export type Price = number | null;
export type AveragePrice = number | null;
export type Reason = string | null;
export type TimeInForce = string | null;
export type Error = string | null;
export type UpdatedAt = string | null;
export type Leverage = number | null;
export type OperatorPublicId4 = string | null;
export type UserPublicId2 = string | null;
export type PlanPublicId = string | null;
export type Type21 = "order_event";
export type Topic22 = string | null;
export type Exchange5 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Event1 = "submitted" | "accepted" | "rejected" | "cancelled" | "expired" | "replaced";
export type Reason1 = string | null;
export type OperatorPublicId5 = string | null;
export type UserPublicId3 = string | null;
export type Type22 = "order_replace";
export type Topic23 = string | null;
export type Exchange6 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type NewQuantity = number | null;
export type NewPrice = number | null;
export type OperatorPublicId6 = string | null;
export type UserPublicId4 = string | null;
export type Type23 = "order_request";
export type Topic24 = string | null;
export type Exchange7 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode2 = "live" | "paper";
export type Side2 = "buy" | "sell";
export type OrderType1 = "market" | "limit" | "stop" | "stop_limit";
export type Price1 = number | null;
export type SignaledAt = string | null;
export type StrategyTag = string | null;
export type Leverage1 = number | null;
export type OperatorPublicId7 = string | null;
export type UserPublicId5 = string | null;
export type Type24 = "position";
export type Topic25 = string | null;
export type Exchange8 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode3 = "live" | "paper";
export type PositionCyclePublicId1 = string | null;
export type Type25 = "replay_end";
export type Topic26 = string | null;
export type Type26 = "replay_start";
export type Topic27 = string | null;
export type StartedAt = string | null;
export type Type27 = "scope_revoked";
export type Topic28 = string | null;
export type ScopeKind = "underlying" | "instrument";
export type UnderlyingPublicId = string | null;
export type InstrumentPublicId = string | null;
export type RevokedByUserPublicId = string | null;
export type Reason2 = string | null;
export type Type28 = "setting_changed";
export type Topic29 = string | null;
export type UpdatedBy = string | null;
export type Type29 = "signal";
export type Topic30 = string | null;
export type Exchange9 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Side3 = "buy" | "sell";
export type Price2 = number | null;
export type StrategyName = string | null;
export type OperatorPublicId8 = string | null;
export type UserPublicId6 = string | null;
export type AiReviewPublicId = string | null;
export type AiReviewDispatchVersion = number | null;
export type Type30 = "symbol_alias_update";
export type Topic31 = string | null;
export type Event2 = "symbol_aliases_updated";
export type Action = "clear_cache";
export type Type31 = "tick";
export type Topic32 = string | null;
export type Exchange10 = "kraken" | "kraken_futures" | "kraken_equities" | "walutomat" | "polygon";
export type Bid = number | null;
export type Ask = number | null;
export type Last = number | null;
export type IsExtendedHours = boolean | null;
export type Type32 = "trade";
export type Topic33 = string | null;
export type Exchange11 = "kraken" | "kraken_futures" | "kraken_equities" | "walutomat" | "polygon";
export type ExecutedAt = string | null;
export type Side4 = string | null;
export type TradeId1 = string | null;
export type Type33 = "underlying_asset";
export type Topic34 = string | null;
export type Sector = string | null;
export type Type34 = "underlying_instrument";
export type Topic35 = string | null;
export type ContractFamily2 = string | null;
export type Type35 = "user_deactivated";
export type Topic36 = string | null;
export type Reason3 = string | null;
export type Type36 = "venue_fee_schedule";
export type Topic37 = string | null;
export type InstrumentPublicId1 = string | null;
export type MinVolume30D = number | null;
export type Type37 = "auth_complete";
export type Topic38 = string | null;
export type AvailableTopics = string[];
export type UserRole = "ai_delegate" | "viewer" | "operator" | "admin";
export type SessionExpiresAt = string | null;
export type Type38 = "auth_expired";
export type Topic39 = string | null;
export type Type39 = "auth_failed";
export type Topic40 = string | null;
export type Reason4 = string | null;
export type Type40 = "auth_ok";
export type Topic41 = string | null;
export type Type41 = "auth_required";
export type Topic42 = string | null;
export type Type42 = "authenticate";
export type Topic43 = string | null;
export type Type43 = "error";
export type Topic44 = string | null;
export type Type44 = "get_subscriptions";
export type Topic45 = string | null;
export type Type45 = "ping";
export type Topic46 = string | null;
export type Type46 = "pong";
export type Topic47 = string | null;
export type Type47 = "reauth_ok";
export type Topic48 = string | null;
export type Type48 = "reauth";
export type Topic49 = string | null;
export type Type49 = "reauth_required";
export type Topic50 = string | null;
export type Type50 = "subscribe";
export type Topic51 = string | null;
export type Topics = string[];
export type Type51 = "subscription_success";
export type Topic52 = string | null;
export type Action1 = "subscribe" | "unsubscribe";
export type Status2 = "subscribed" | "unsubscribed" | "partial" | "denied" | "no_topics";
export type Topics1 = string[];
export type DeniedTopics = string[];
export type ActiveSubscriptions = string[];
export type Message = string | null;
export type Type52 = "subscriptions_list";
export type Topic53 = string | null;
export type Subscriptions = string[];
export type AvailableTopics1 = string[];
export type Type53 = "unsubscribe";
export type Topic54 = string | null;
export type Topics2 = string[];

export interface StrictDataSchema {
  type: string;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic;
}
export interface AiReviewCapsViolationFrameData {
  type: Type;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic1;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  cap_type: string;
  attempted: number;
  limit: number;
  dispatch_version: number;
}
export interface AiReviewDecisionAckFrameData {
  type: Type1;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic2;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  responding_delegate_public_id: string;
  decision: string;
  new_status: string;
  resolution_mode: string;
  rationale: Rationale;
  dispatch_version: number;
}
export interface AiReviewDecisionData {
  type: Type2;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic3;
  review_public_id: string;
  responding_delegate_public_id: string;
  decision: string;
  new_status: string;
  resolution_mode: string;
  dispatch_version: number;
}
export interface AiReviewRequestFrameData {
  type: Type3;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic4;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  selected_delegate_public_id: string;
  deadline: string;
  signal_envelope: JsonObject;
  instrument_metadata: JsonObject;
  dispatch_version: number;
}
export interface JsonObject {
  [k: string]: JsonValue;
}
export interface AlertEventData {
  type: Type4;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic5;
  user_public_id: string;
  operator_public_id?: OperatorPublicId;
  wallet_public_id?: WalletPublicId;
  alert_type: AlertType;
  priority?: Priority;
  is_safety_critical?: boolean;
  title: string;
  body: string;
  payload?: JsonObject | null;
  dedup_key?: DedupKey;
  thread_key?: ThreadKey;
  source_topic?: SourceTopic;
}
export interface BacktestProgressData {
  type: Type5;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic6;
  run_public_id: string;
  wallet_public_id: string;
  event: Event;
  milestone?: Milestone;
  candles_done: number;
  total_candles: TotalCandles;
  signals_count: number;
  trades_count: number;
  equity: number;
  progress_pct: number;
}
export interface CandleData {
  type: Type6;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic7;
  instrument: string;
  exchange: Exchange;
  timeframe: string;
  open_at: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  vwap?: Vwap;
  trades?: Trades;
}
export interface CapsViolationAfterAiApproveData {
  type: Type7;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic8;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  cap_type: string;
  attempted: number;
  limit: number;
  dispatch_version: number;
}
export interface ContinuousCandleData {
  type: Type8;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic9;
  open_at: string;
  timeframe: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  vwap: Vwap1;
  trades: Trades1;
  source_contract: string;
  adjustment_factor: AdjustmentFactor;
}
export interface ContractData {
  type: Type9;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic10;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  expiry_at: ExpiryAt;
  instrument_kind: InstrumentKind;
  relationship_type: string;
  contract_family: ContractFamily;
  is_front_month: boolean;
}
export interface DelegateOfflineData {
  type: Type10;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic11;
  user_public_id: string;
  delegate_public_id: string;
  last_seen_at: string;
}
export interface ExecutionData {
  type: Type11;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic12;
  trade_id?: TradeId;
  exchange_order_id?: ExchangeOrderId;
  client_order_id: string;
  instrument: string;
  exchange: Exchange1;
  side: Side;
  size: number;
  price: number;
  last_size: number;
  last_price: number;
  fee: number;
  fee_asset: string;
  status: Status;
  executed_at: string;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId1;
  user_public_id?: UserPublicId;
  liquidity_role?: string;
}
export interface ExecutionPlanData {
  type: Type12;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic13;
  plan_type: string;
  status: string;
  instrument_public_id: string;
  exchange: string;
  mode: string;
  side: string;
  total_quantity: number;
  filled_quantity: number;
  created_at: string;
  created_via: string;
  wallet_public_id: string;
  operator_public_id: OperatorPublicId2;
  params: Params;
  position_cycle_public_id: PositionCyclePublicId;
  parent_plan_public_id: ParentPlanPublicId;
  last_error: LastError;
  idempotency_key: IdempotencyKey;
}
export interface Params {
  [k: string]: unknown;
}
export interface ExecutionPlanDecisionEventData {
  type: Type13;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic14;
  decision_public_id: string;
  plan_public_id: string;
  decision_type: string;
  trigger_type: string;
  reason: string;
  triggered_at: string;
}
export interface FrontMonthData {
  type: Type14;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic15;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  expiry_at: string;
  relationship_type: string;
  contract_family: ContractFamily1;
}
export interface FundingAccrualData {
  type: Type15;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic16;
  instrument: string;
  exchange: Exchange2;
  mode: Mode;
  accrual_type: AccrualType;
  accrued_at: string;
  amount: number;
  amount_asset: string;
  rate: number;
  notional: number;
  position_quantity: number;
}
export interface HeartbeatData {
  type: Type16;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic17;
  component: string;
  sequence: number;
  status: Status1;
  lag_ms: number;
  meta?: JsonObject1;
}
export interface JsonObject1 {
  [k: string]: JsonValue;
}
export interface InstrumentCapabilityData {
  type: Type17;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic18;
  instrument_public_id: string;
  exchange: string;
  supported_order_types: SupportedOrderTypes;
  supports_post_only: boolean;
  supports_reduce_only: boolean;
  supports_amend_in_place: boolean;
  supports_native_stop_loss: boolean;
  supports_native_take_profit: boolean;
  supports_trailing_stop_client_side: boolean;
  supports_market_making: boolean;
  supports_short_selling: boolean;
  supports_leverage: boolean;
  max_leverage_long: number;
  max_leverage_short: number;
  min_notional: MinNotional;
  max_order_size: MaxOrderSize;
  top_of_book_quality: string;
}
export interface InstrumentDetailData {
  type: Type18;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic19;
  instrument_public_id: string;
  symbol_public_id: string;
  symbol: string;
  exchange: string;
  can_trade: boolean;
  can_market_data: boolean;
  instrument_resolved: boolean;
  instrument_kind: InstrumentKind1;
  expiry_at: ExpiryAt1;
}
export interface OrderCancelData {
  type: Type19;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic20;
  exchange: Exchange3;
  instrument: string;
  exchange_order_id: string;
  client_order_id: string;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId3;
  user_public_id?: UserPublicId1;
}
export interface OrderData {
  type: Type20;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic21;
  exchange_order_id?: ExchangeOrderId1;
  client_order_id: string;
  instrument: string;
  exchange: Exchange4;
  mode?: Mode1;
  side: Side1;
  status: string;
  order_type: OrderType;
  size: number;
  filled_size: number;
  price?: Price;
  average_price?: AveragePrice;
  reason?: Reason;
  time_in_force?: TimeInForce;
  error?: Error;
  created_at: string;
  updated_at?: UpdatedAt;
  leverage?: Leverage;
  reduce_only?: boolean;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId4;
  user_public_id?: UserPublicId2;
  plan_public_id?: PlanPublicId;
}
export interface OrderEventData {
  type: Type21;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic22;
  exchange_order_id: string;
  client_order_id: string;
  exchange: Exchange5;
  instrument: string;
  event: Event1;
  reason?: Reason1;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId5;
  user_public_id?: UserPublicId3;
}
export interface OrderReplaceData {
  type: Type22;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic23;
  exchange: Exchange6;
  instrument: string;
  exchange_order_id: string;
  client_order_id: string;
  new_quantity?: NewQuantity;
  new_price?: NewPrice;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId6;
  user_public_id?: UserPublicId4;
}
export interface OrderRequestData {
  type: Type23;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic24;
  strategy_id: string;
  exchange: Exchange7;
  instrument: string;
  mode: Mode2;
  side: Side2;
  order_type: OrderType1;
  quantity: number;
  price?: Price1;
  client_order_id: string;
  signaled_at?: SignaledAt;
  strategy_tag?: StrategyTag;
  leverage?: Leverage1;
  reduce_only?: boolean;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId7;
  user_public_id?: UserPublicId5;
}
export interface PositionData {
  type: Type24;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic25;
  instrument: string;
  instrument_public_id?: string;
  exchange: Exchange8;
  mode?: Mode3;
  quantity: number;
  average_price: number;
  unrealized_pnl: number;
  realized_pnl: number;
  position_cycle_public_id?: PositionCyclePublicId1;
  wallet_public_id?: string;
}
export interface ReplayEndData {
  type: Type25;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic26;
}
export interface ReplayStartData {
  type: Type26;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic27;
  started_at?: StartedAt;
}
export interface ScopeRevokedData {
  type: Type27;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic28;
  grant_public_id: string;
  operator_public_id: string;
  wallet_public_id: string;
  scope_kind: ScopeKind;
  underlying_public_id?: UnderlyingPublicId;
  instrument_public_id?: InstrumentPublicId;
  revoked_at: string;
  revoked_by_user_public_id?: RevokedByUserPublicId;
  reason?: Reason2;
}
export interface SettingChangedData {
  type: Type28;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic29;
  key: string;
  value: string;
  category: string;
  updated_by?: UpdatedBy;
}
export interface SignalData {
  type: Type29;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic30;
  instrument: string;
  exchange: Exchange9;
  side: Side3;
  strength: number;
  reason: string;
  price?: Price2;
  strategy_name?: StrategyName;
  fired_at: string;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId8;
  user_public_id?: UserPublicId6;
  ai_review_public_id?: AiReviewPublicId;
  ai_review_dispatch_version?: AiReviewDispatchVersion;
}
export interface SymbolAliasUpdateData {
  type: Type30;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic31;
  event: Event2;
  action: Action;
}
export interface TickData {
  type: Type31;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic32;
  instrument: string;
  exchange: Exchange10;
  volume: number;
  bid?: Bid;
  ask?: Ask;
  last?: Last;
  is_delayed?: boolean;
  is_extended_hours?: IsExtendedHours;
}
export interface TradeData {
  type: Type32;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic33;
  instrument: string;
  exchange: Exchange11;
  executed_at?: ExecutedAt;
  price: number;
  volume: number;
  side?: Side4;
  trade_id?: TradeId1;
}
export interface UnderlyingAssetData {
  type: Type33;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic34;
  ticker: string;
  name: string;
  asset_class: string;
  sector: Sector;
  instrument_count: number;
}
export interface UnderlyingInstrumentData {
  type: Type34;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic35;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  asset_type: string;
  relationship_type: string;
  contract_family: ContractFamily2;
}
export interface UserDeactivatedData {
  type: Type35;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic36;
  user_public_id: string;
  deactivated_at: string;
  reason?: Reason3;
}
export interface VenueFeeScheduleData {
  type: Type36;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic37;
  exchange: string;
  instrument_public_id: InstrumentPublicId1;
  fee_tier: string;
  maker_bps: number;
  taker_bps: number;
  min_volume_30d: MinVolume30D;
  currency: string;
}
export interface WSAuthCompleteResponse {
  type: Type37;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic38;
  available_topics: AvailableTopics;
  user_role: UserRole;
  session_expires_at?: SessionExpiresAt;
  ws_token_exp: string;
}
export interface WSAuthExpiredResponse {
  type: Type38;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic39;
}
export interface WSAuthFailedResponse {
  type: Type39;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic40;
  reason?: Reason4;
}
export interface WSAuthOkResponse {
  type: Type40;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic41;
  exp: string;
}
export interface WSAuthRequiredResponse {
  type: Type41;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic42;
  timeout?: number;
}
export interface WSAuthenticateRequest {
  type: Type42;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic43;
  ws_token: string;
}
export interface WSErrorResponse {
  type: Type43;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic44;
  message: string;
}
export interface WSGetSubscriptionsRequest {
  type: Type44;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic45;
}
export interface WSPingRequest {
  type: Type45;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic46;
}
export interface WSPongResponse {
  type: Type46;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic47;
  active_connections: number;
}
export interface WSReauthOkResponse {
  type: Type47;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic48;
  exp: string;
}
export interface WSReauthRequest {
  type: Type48;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic49;
  ws_token: string;
}
export interface WSReauthRequiredResponse {
  type: Type49;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic50;
  deadline: string;
}
export interface WSSubscribeRequest {
  type: Type50;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic51;
  topics: Topics;
}
export interface WSSubscriptionSuccessResponse {
  type: Type51;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic52;
  action: Action1;
  status: Status2;
  topics: Topics1;
  denied_topics?: DeniedTopics;
  active_subscriptions: ActiveSubscriptions;
  message?: Message;
}
export interface WSSubscriptionsListResponse {
  type: Type52;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic53;
  subscriptions: Subscriptions;
  available_topics: AvailableTopics1;
  total_available: number;
}
export interface WSUnsubscribeRequest {
  type: Type53;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic54;
  topics: Topics2;
}
