/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebSocketMessages =
  | StrictDataSchema
  | AccountStateChangedEventData
  | AiReviewCapsViolationFrameData
  | AiReviewDecisionAckFrameData
  | AiReviewDecisionData
  | AiReviewRequestFrameData
  | AlertEventData
  | BacktestProgressData
  | CandleData
  | CapsViolationAfterAiApproveData
  | ContinuousCandleData
  | ContractData
  | DelegateOfflineData
  | EgressPoolSnapshotEventData
  | EgressTransferEventData
  | ExecutionData
  | ExecutionPlanData
  | ExecutionPlanDecisionData
  | ExecutionPlanDecisionEventData
  | FrontMonthData
  | FundingAccrualData
  | HeartbeatData
  | InstrumentCapabilityData
  | InstrumentDetailData
  | OrderCancelData
  | OrderData
  | OrderEventData
  | OrderReplaceData
  | OrderRequestData
  | PortfolioDriftEpisodeEventData
  | PositionData
  | ProcessCommandAckData
  | ProcessCommandData
  | ProcessConfiguredEventData
  | ProcessRunEventData
  | ProcessSummaryEventData
  | RelatedInstrumentData
  | ReplayEndData
  | ReplayStartData
  | ScopeGrantedData
  | ScopeHandedOverData
  | ScopeRevokedData
  | SettingChangedData
  | SignalData
  | StrategyListEventData
  | SymbolAliasUpdateData
  | TickData
  | TradeData
  | UnderlyingAssetData
  | UnderlyingInstrumentData
  | UserDeactivatedData
  | VenueFeeScheduleData
  | WSAuthCompleteResponse
  | WSAuthExpiredResponse
  | WSAuthFailedResponse
  | WSAuthOkResponse
  | WSAuthRequiredResponse
  | WSAuthenticateRequest
  | WSErrorResponse
  | WSGetSubscriptionsRequest
  | WSPingRequest
  | WSPongResponse
  | WSReauthOkResponse
  | WSReauthRequest
  | WSReauthRequiredResponse
  | WSSubscribeRequest
  | WSSubscriptionSuccessResponse
  | WSSubscriptionsListResponse
  | WSUnsubscribeRequest;
export type Topic = string | null;
export type Type = "account_state_changed_event";
export type Topic1 = string | null;
export type Exchange = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode = "live" | "paper";
export type Kind = "snapshot" | "reconciliation";
export type Type1 = "ai_review.caps_violation";
export type Topic2 = string | null;
export type Type2 = "ai_review.decision_ack";
export type Topic3 = string | null;
export type Rationale = string | null;
export type Type3 = "ai_review_decision";
export type Topic4 = string | null;
export type Type4 = "ai_review.request";
export type Topic5 = string | null;
export type JsonValue =
  | JsonPrimitive
  | JsonValue[]
  | {
      [k: string]: JsonValue;
    };
export type JsonPrimitive = string | number | boolean | null;
export type Type5 = "alert_event";
export type Topic6 = string | null;
export type OperatorPublicId = string | null;
export type WalletPublicId = string | null;
export type AlertType =
  | "order_fill_full"
  | "order_rejected"
  | "order_unknown"
  | "position_stop_loss_fired"
  | "margin_warning"
  | "critical_system_error"
  | "drift";
export type Priority = "low" | "medium" | "high";
export type DedupKey = string | null;
export type ThreadKey = string | null;
export type SourceTopic = string | null;
export type Type6 = "backtest_progress";
export type Topic7 = string | null;
export type Event = "started" | "progress" | "milestone" | "completed" | "failed" | "cancelled";
export type Milestone = ("25pct" | "50pct" | "75pct") | null;
export type TotalCandles = number | null;
export type Type7 = "candle";
export type Topic8 = string | null;
export type Exchange1 = "kraken" | "kraken_futures" | "kraken_equities" | "walutomat" | "polygon";
export type Vwap = number | null;
export type Trades = number | null;
export type Origin = "live" | "replay";
export type ReplayWindowStart = string | null;
export type ReplayWindowEnd = string | null;
export type Type8 = "caps_violation_after_ai_approve";
export type Topic9 = string | null;
export type Type9 = "continuous_candle";
export type Topic10 = string | null;
export type Vwap1 = number | null;
export type Trades1 = number | null;
export type AdjustmentFactor = number | null;
export type Type10 = "contract";
export type Topic11 = string | null;
export type ExpiryAt = string | null;
export type InstrumentKind = string | null;
export type ContractFamily = string | null;
export type Type11 = "delegate_offline";
export type Topic12 = string | null;
export type Type12 = "egress_pool_snapshot_event";
export type Topic13 = string | null;
export type OnAllQuarantined = ("wait" | "raise") | null;
export type PrivateFallbackRouteId = string | null;
export type Kind1 = "direct" | "socks5";
export type ProxyUrl = string | null;
export type Region = string | null;
export type ExitIp = string | null;
export type Provider = string | null;
export type AllowedExchanges = string[];
export type QuarantineSecondsRemaining = number | null;
export type TrafficClass = "public" | "private";
export type ActiveReservations = EgressActiveReservationSnapshot[];
export type Kind2 = "ws" | "rest";
export type TrafficClass1 = "public" | "private";
export type LastSeenAt = string | null;
export type Connections = EgressConnectionSnapshot[];
export type RxRateBytesPerSecond = number | null;
export type TxRateBytesPerSecond = number | null;
export type LatestHandshakeAt = string | null;
export type Routes = EgressRouteStatusSnapshot[];
export type Type13 = "egress_transfer_event";
export type Topic14 = string | null;
export type RxRateBytesPerSecond1 = number | null;
export type TxRateBytesPerSecond1 = number | null;
export type LatestHandshakeAt1 = string | null;
export type Interfaces = EgressTransferInterfaceSnapshot[];
export type Type14 = "execution";
export type Topic15 = string | null;
export type TradeId = string | null;
export type ExchangeOrderId = string | null;
export type Exchange2 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Side = "buy" | "sell";
export type Status = "filled" | "partial";
export type OperatorPublicId1 = string | null;
export type UserPublicId = string | null;
export type PairedGroupId = string | null;
export type PairedGroupSize = number | null;
export type PairedGroupIndex = number | null;
export type PairedGroupPolicy = ("simultaneous" | "sequential_handoff") | null;
export type Type15 = "execution_plan";
export type Topic16 = string | null;
export type OperatorPublicId2 = string | null;
export type PositionCyclePublicId = string | null;
export type ParentPlanPublicId = string | null;
export type LastError = string | null;
export type IdempotencyKey = string | null;
export type Type16 = "execution_plan_decision";
export type Topic17 = string | null;
export type EmittedCommandPublicId = string | null;
export type NewStatus = string | null;
export type Type17 = "execution_plan_decision_event";
export type Topic18 = string | null;
export type Type18 = "front_month";
export type Topic19 = string | null;
export type ContractFamily1 = string | null;
export type Type19 = "funding_accrual";
export type Topic20 = string | null;
export type Exchange3 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode1 = "live" | "paper";
export type AccrualType = "funding" | "rollover" | "borrow";
export type Type20 = "heartbeat";
export type Topic21 = string | null;
export type Status1 = "healthy" | "warning" | "error";
export type NextOpen = string | null;
export type Type21 = "instrument_capability";
export type Topic22 = string | null;
export type SupportedOrderTypes = string[];
export type MinNotional = number | null;
export type MaxOrderSize = number | null;
export type Type22 = "instrument_detail";
export type Topic23 = string | null;
export type InstrumentKind1 = string | null;
export type ExpiryAt1 = string | null;
export type Type23 = "order_cancel";
export type Topic24 = string | null;
export type Exchange4 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type OperatorPublicId3 = string | null;
export type UserPublicId1 = string | null;
export type Type24 = "order";
export type Topic25 = string | null;
export type ExchangeOrderId1 = string | null;
export type Exchange5 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode2 = "live" | "paper";
export type Side1 = "buy" | "sell";
export type OrderType = "market" | "limit" | "stop" | "stop_limit";
export type Price = number | null;
export type AveragePrice = number | null;
export type Reason = string | null;
export type TimeInForce = string | null;
export type Error = string | null;
export type UpdatedAt = string | null;
export type Leverage = number | null;
export type OperatorPublicId4 = string | null;
export type UserPublicId2 = string | null;
export type PlanPublicId = string | null;
export type PairedGroupId1 = string | null;
export type PairedGroupSize1 = number | null;
export type PairedGroupIndex1 = number | null;
export type PairedGroupPolicy1 = ("simultaneous" | "sequential_handoff") | null;
export type Type25 = "order_event";
export type Topic26 = string | null;
export type Exchange6 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Event1 = "submitted" | "accepted" | "rejected" | "cancelled" | "expired" | "replaced" | "unknown";
export type Reason1 = string | null;
export type OperatorPublicId5 = string | null;
export type UserPublicId3 = string | null;
export type PairedGroupId2 = string | null;
export type PairedGroupSize2 = number | null;
export type PairedGroupIndex2 = number | null;
export type PairedGroupPolicy2 = ("simultaneous" | "sequential_handoff") | null;
export type Type26 = "order_replace";
export type Topic27 = string | null;
export type Exchange7 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type NewQuantity = number | null;
export type NewPrice = number | null;
export type OperatorPublicId6 = string | null;
export type UserPublicId4 = string | null;
export type Type27 = "order_request";
export type Topic28 = string | null;
export type Exchange8 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode3 = "live" | "paper";
export type Side2 = "buy" | "sell";
export type OrderType1 = "market" | "limit" | "stop" | "stop_limit";
export type Price1 = number | null;
export type StopPrice = number | null;
export type SignaledAt = string | null;
export type StrategyTag = string | null;
export type Leverage1 = number | null;
export type OperatorPublicId7 = string | null;
export type UserPublicId5 = string | null;
export type PairedGroupId3 = string | null;
export type PairedGroupSize3 = number | null;
export type PairedGroupIndex3 = number | null;
export type PairedGroupPolicy3 = ("simultaneous" | "sequential_handoff") | null;
export type Origin1 = "live" | "replay";
export type ReplayWindowStart1 = string | null;
export type ReplayWindowEnd1 = string | null;
export type Type28 = "portfolio_drift_episode_event";
export type Topic29 = string | null;
export type Mode4 = "live";
export type Lifecycle = "opened" | "resolved";
export type ClosedAt = string | null;
export type ResolutionReason = "matched" | null;
export type Type29 = "position";
export type Topic30 = string | null;
export type Exchange9 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Mode5 = "live" | "paper";
export type AveragePrice1 = number | null;
export type UnrealizedPnl = number | null;
export type MarkPrice = number | null;
export type MarkedAt = string | null;
export type SourceVenueEventId = number | null;
export type PositionCyclePublicId1 = string | null;
export type Type30 = "process_command_ack";
export type Topic31 = string | null;
export type Detail = string | null;
export type Type31 = "process_command";
export type Topic32 = string | null;
export type Type32 = "process_configured_event";
export type Topic33 = string | null;
export type ProcessNames = string[];
export type Type33 = "process_run_event";
export type Topic34 = string | null;
export type CompletedAt = string | null;
export type ExitCode = number | null;
export type Type34 = "process_summary_event";
export type Topic35 = string | null;
export type CoordinatorLabel = string | null;
export type ActivePublicId = string | null;
export type RssBytes = number | null;
export type CpuPercent = number | null;
export type Processes = ProcessSummaryItem[];
export type Type35 = "related_instrument";
export type Topic36 = string | null;
export type ContractFamily2 = string | null;
export type Type36 = "replay_end";
export type Topic37 = string | null;
export type Type37 = "replay_start";
export type Topic38 = string | null;
export type StartedAt = string | null;
export type Type38 = "scope_granted";
export type Topic39 = string | null;
export type ScopeKind = "underlying" | "instrument";
export type UnderlyingPublicId = string | null;
export type InstrumentPublicId = string | null;
export type Reason2 = string | null;
export type Type39 = "scope_handed_over";
export type Topic40 = string | null;
export type ScopeKind1 = "underlying" | "instrument";
export type UnderlyingPublicId1 = string | null;
export type InstrumentPublicId1 = string | null;
export type Reason3 = string | null;
export type Type40 = "scope_revoked";
export type Topic41 = string | null;
export type ScopeKind2 = "underlying" | "instrument";
export type UnderlyingPublicId2 = string | null;
export type InstrumentPublicId2 = string | null;
export type RevokedByUserPublicId = string | null;
export type Reason4 = string | null;
export type Type41 = "setting_changed";
export type Topic42 = string | null;
export type UpdatedBy = string | null;
export type Type42 = "signal";
export type Topic43 = string | null;
export type Exchange10 = "paper" | "kraken" | "kraken_futures" | "walutomat";
export type Side3 = "buy" | "sell";
export type Price2 = number | null;
export type StrategyName = string | null;
export type OperatorPublicId8 = string | null;
export type UserPublicId6 = string | null;
export type AiReviewPublicId = string | null;
export type AiReviewDispatchVersion = number | null;
export type PairedGroupId4 = string | null;
export type PairedGroupSize4 = number | null;
export type PairedGroupIndex4 = number | null;
export type PairedGroupPolicy4 = ("simultaneous" | "sequential_handoff") | null;
export type PairedGroupKey = string | null;
export type Origin2 = "live" | "replay";
export type ReplayWindowStart2 = string | null;
export type ReplayWindowEnd2 = string | null;
export type Type43 = "strategy_list_event";
export type Topic44 = string | null;
export type StrategyClasses = string[];
export type Type44 = "symbol_alias_update";
export type Topic45 = string | null;
export type Event2 = "symbol_aliases_updated";
export type Action = "clear_cache";
export type Type45 = "tick";
export type Topic46 = string | null;
export type Exchange11 = "kraken" | "kraken_futures" | "kraken_equities" | "walutomat" | "polygon";
export type Bid = number | null;
export type Ask = number | null;
export type Last = number | null;
export type IsExtendedHours = boolean | null;
export type Origin3 = "live" | "replay";
export type ReplayWindowStart3 = string | null;
export type ReplayWindowEnd3 = string | null;
export type Type46 = "trade";
export type Topic47 = string | null;
export type Exchange12 = "kraken" | "kraken_futures" | "kraken_equities" | "walutomat" | "polygon";
export type ExecutedAt = string | null;
export type Side4 = string | null;
export type TradeId1 = string | null;
export type Origin4 = "live" | "replay";
export type ReplayWindowStart4 = string | null;
export type ReplayWindowEnd4 = string | null;
export type Type47 = "underlying_asset";
export type Topic48 = string | null;
export type Sector = string | null;
export type Description = string | null;
export type Type48 = "underlying_instrument";
export type Topic49 = string | null;
export type ContractFamily3 = string | null;
export type Type49 = "user_deactivated";
export type Topic50 = string | null;
export type Reason5 = string | null;
export type Type50 = "venue_fee_schedule";
export type Topic51 = string | null;
export type InstrumentPublicId3 = string | null;
export type MinVolume30D = number | null;
export type Type51 = "auth_complete";
export type Topic52 = string | null;
export type AvailableTopics = string[];
export type UserRole = "ai_researcher" | "ai_delegate" | "viewer" | "operator" | "admin";
export type SessionExpiresAt = string | null;
export type Type52 = "auth_expired";
export type Topic53 = string | null;
export type Type53 = "auth_failed";
export type Topic54 = string | null;
export type Reason6 = string | null;
export type Type54 = "auth_ok";
export type Topic55 = string | null;
export type Type55 = "auth_required";
export type Topic56 = string | null;
export type Type56 = "authenticate";
export type Topic57 = string | null;
export type Type57 = "error";
export type Topic58 = string | null;
export type Type58 = "get_subscriptions";
export type Topic59 = string | null;
export type Type59 = "ping";
export type Topic60 = string | null;
export type Type60 = "pong";
export type Topic61 = string | null;
export type Type61 = "reauth_ok";
export type Topic62 = string | null;
export type Type62 = "reauth";
export type Topic63 = string | null;
export type Type63 = "reauth_required";
export type Topic64 = string | null;
export type Type64 = "subscribe";
export type Topic65 = string | null;
export type Topics = string[];
export type Type65 = "subscription_success";
export type Topic66 = string | null;
export type Action1 = "subscribe" | "unsubscribe";
export type Status2 = "subscribed" | "unsubscribed" | "partial" | "denied" | "no_topics";
export type Topics1 = string[];
export type DeniedTopics = string[];
export type ActiveSubscriptions = string[];
export type Message = string | null;
export type Type66 = "subscriptions_list";
export type Topic67 = string | null;
export type Subscriptions = string[];
export type AvailableTopics1 = string[];
export type Type67 = "unsubscribe";
export type Topic68 = string | null;
export type Topics2 = string[];

export interface StrictDataSchema {
  type: string;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic;
}
export interface AccountStateChangedEventData {
  type: Type;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic1;
  wallet_public_id: string;
  exchange: Exchange;
  mode: Mode;
  kind: Kind;
}
export interface AiReviewCapsViolationFrameData {
  type: Type1;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic2;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  cap_type: string;
  attempted: number;
  limit: number;
  dispatch_version: number;
}
export interface AiReviewDecisionAckFrameData {
  type: Type2;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic3;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  responding_delegate_public_id: string;
  decision: string;
  new_status: string;
  resolution_mode: string;
  rationale: Rationale;
  dispatch_version: number;
}
export interface AiReviewDecisionData {
  type: Type3;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic4;
  review_public_id: string;
  responding_delegate_public_id: string;
  decision: string;
  new_status: string;
  resolution_mode: string;
  dispatch_version: number;
}
export interface AiReviewRequestFrameData {
  type: Type4;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic5;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  selected_delegate_public_id: string;
  deadline: string;
  signal_envelope: JsonObject;
  instrument_metadata: JsonObject;
  dispatch_version: number;
}
export interface JsonObject {
  [k: string]: JsonValue;
}
export interface AlertEventData {
  type: Type5;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic6;
  user_public_id: string;
  operator_public_id?: OperatorPublicId;
  wallet_public_id?: WalletPublicId;
  alert_type: AlertType;
  priority?: Priority;
  is_safety_critical?: boolean;
  title: string;
  body: string;
  payload?: JsonObject | null;
  dedup_key?: DedupKey;
  thread_key?: ThreadKey;
  source_topic?: SourceTopic;
}
export interface BacktestProgressData {
  type: Type6;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic7;
  run_public_id: string;
  wallet_public_id: string;
  event: Event;
  milestone?: Milestone;
  candles_done: number;
  total_candles: TotalCandles;
  signals_count: number;
  trades_count: number;
  equity: number;
  progress_pct: number;
}
export interface CandleData {
  type: Type7;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic8;
  instrument: string;
  exchange: Exchange1;
  timeframe: string;
  open_at: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  vwap?: Vwap;
  trades?: Trades;
  complete?: boolean;
  origin?: Origin;
  replay_window_start?: ReplayWindowStart;
  replay_window_end?: ReplayWindowEnd;
}
export interface CapsViolationAfterAiApproveData {
  type: Type8;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic9;
  review_public_id: string;
  user_public_id: string;
  strategy_public_id: string;
  wallet_public_id: string;
  instrument_public_id: string;
  cap_type: string;
  attempted: number;
  limit: number;
  dispatch_version: number;
}
export interface ContinuousCandleData {
  type: Type9;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic10;
  open_at: string;
  timeframe: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  vwap: Vwap1;
  trades: Trades1;
  source_contract: string;
  adjustment_factor: AdjustmentFactor;
}
export interface ContractData {
  type: Type10;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic11;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  expiry_at: ExpiryAt;
  instrument_kind: InstrumentKind;
  relationship_type: string;
  contract_family: ContractFamily;
  is_front_month: boolean;
}
export interface DelegateOfflineData {
  type: Type11;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic12;
  user_public_id: string;
  delegate_public_id: string;
  last_seen_at: string;
}
export interface EgressPoolSnapshotEventData {
  type: Type12;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic13;
  container: string;
  snapshot: EgressPoolStatusSnapshot;
}
export interface EgressPoolStatusSnapshot {
  enabled: boolean;
  on_all_quarantined?: OnAllQuarantined;
  private_fallback_route_id?: PrivateFallbackRouteId;
  private_on_fallback?: boolean;
  routes?: Routes;
}
export interface EgressRouteStatusSnapshot {
  id: string;
  kind: Kind1;
  proxy_url?: ProxyUrl;
  region?: Region;
  exit_ip?: ExitIp;
  provider?: Provider;
  priority: number;
  allowed_exchanges?: AllowedExchanges;
  enabled: boolean;
  quarantined: boolean;
  quarantine_seconds_remaining: QuarantineSecondsRemaining;
  in_use_count: number;
  active_reservations?: ActiveReservations;
  connections?: Connections;
  transfer?: EgressTransferSnapshot | null;
}
export interface EgressActiveReservationSnapshot {
  exchange: string;
  traffic_class: TrafficClass;
  container?: string;
}
export interface EgressConnectionSnapshot {
  host: string;
  kind: Kind2;
  exchange: string;
  traffic_class: TrafficClass1;
  container?: string;
  count: number;
  last_seen_at?: LastSeenAt;
}
export interface EgressTransferSnapshot {
  interface: string;
  socks5_listen_port: number;
  rx_bytes: number;
  tx_bytes: number;
  rx_rate_bytes_per_second?: RxRateBytesPerSecond;
  tx_rate_bytes_per_second?: TxRateBytesPerSecond;
  latest_handshake_at?: LatestHandshakeAt;
  counter_reset: boolean;
  sampled_at: string;
  sample_age_seconds: number;
  stale: boolean;
}
export interface EgressTransferEventData {
  type: Type13;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic14;
  interfaces?: Interfaces;
}
export interface EgressTransferInterfaceSnapshot {
  interface: string;
  socks5_listen_port: number;
  rx_bytes: number;
  tx_bytes: number;
  rx_rate_bytes_per_second?: RxRateBytesPerSecond1;
  tx_rate_bytes_per_second?: TxRateBytesPerSecond1;
  latest_handshake_at?: LatestHandshakeAt1;
  counter_reset: boolean;
  sampled_at: string;
}
export interface ExecutionData {
  type: Type14;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic15;
  trade_id?: TradeId;
  exchange_order_id?: ExchangeOrderId;
  client_order_id: string;
  instrument: string;
  exchange: Exchange2;
  side: Side;
  size: number;
  price: number;
  last_size: number;
  last_price: number;
  fee: number;
  fee_asset: string;
  status: Status;
  executed_at: string;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId1;
  user_public_id?: UserPublicId;
  liquidity_role?: string;
  paired_group_id?: PairedGroupId;
  paired_group_size?: PairedGroupSize;
  paired_group_index?: PairedGroupIndex;
  paired_group_policy?: PairedGroupPolicy;
}
export interface ExecutionPlanData {
  type: Type15;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic16;
  plan_type: string;
  status: string;
  instrument_public_id: string;
  exchange: string;
  mode: string;
  side: string;
  total_quantity: number;
  filled_quantity: number;
  created_at: string;
  created_via: string;
  wallet_public_id: string;
  operator_public_id: OperatorPublicId2;
  params: Params;
  position_cycle_public_id: PositionCyclePublicId;
  parent_plan_public_id: ParentPlanPublicId;
  last_error: LastError;
  idempotency_key: IdempotencyKey;
}
export interface Params {
  [k: string]: unknown;
}
export interface ExecutionPlanDecisionData {
  type: Type16;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic17;
  plan_public_id: string;
  decision_type: string;
  decided_at: string;
  trigger_type: string;
  evidence?: JsonObject1;
  emitted_command_public_id?: EmittedCommandPublicId;
  new_status?: NewStatus;
  reason: string;
  decision_importance: string;
  source_surface: string;
}
export interface JsonObject1 {
  [k: string]: JsonValue;
}
export interface ExecutionPlanDecisionEventData {
  type: Type17;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic18;
  decision_public_id: string;
  plan_public_id: string;
  decision_type: string;
  trigger_type: string;
  reason: string;
  triggered_at: string;
}
export interface FrontMonthData {
  type: Type18;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic19;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  expiry_at: string;
  relationship_type: string;
  contract_family: ContractFamily1;
}
export interface FundingAccrualData {
  type: Type19;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic20;
  instrument: string;
  exchange: Exchange3;
  mode: Mode1;
  accrual_type: AccrualType;
  accrued_at: string;
  amount: number;
  amount_asset: string;
  rate: number;
  notional: number;
  position_quantity: number;
}
export interface HeartbeatData {
  type: Type20;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic21;
  component: string;
  sequence: number;
  status: Status1;
  lag_ms: number;
  market_closed?: boolean;
  next_open?: NextOpen;
  meta?: JsonObject2;
}
export interface JsonObject2 {
  [k: string]: JsonValue;
}
export interface InstrumentCapabilityData {
  type: Type21;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic22;
  instrument_public_id: string;
  exchange: string;
  supported_order_types: SupportedOrderTypes;
  supports_post_only: boolean;
  supports_reduce_only: boolean;
  supports_amend_in_place: boolean;
  supports_native_stop_loss: boolean;
  supports_native_take_profit: boolean;
  supports_trailing_stop_client_side: boolean;
  supports_market_making: boolean;
  supports_short_selling: boolean;
  supports_leverage: boolean;
  max_leverage_long: number;
  max_leverage_short: number;
  min_notional: MinNotional;
  max_order_size: MaxOrderSize;
  top_of_book_quality: string;
}
export interface InstrumentDetailData {
  type: Type22;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic23;
  instrument_public_id: string;
  symbol_public_id: string;
  symbol: string;
  exchange: string;
  can_trade: boolean;
  can_market_data: boolean;
  instrument_resolved: boolean;
  instrument_kind: InstrumentKind1;
  expiry_at: ExpiryAt1;
}
export interface OrderCancelData {
  type: Type23;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic24;
  exchange: Exchange4;
  instrument: string;
  exchange_order_id: string;
  client_order_id: string;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId3;
  user_public_id?: UserPublicId1;
}
export interface OrderData {
  type: Type24;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic25;
  exchange_order_id?: ExchangeOrderId1;
  client_order_id: string;
  instrument: string;
  exchange: Exchange5;
  mode?: Mode2;
  side: Side1;
  status: string;
  order_type: OrderType;
  size: number;
  filled_size: number;
  price?: Price;
  average_price?: AveragePrice;
  reason?: Reason;
  time_in_force?: TimeInForce;
  error?: Error;
  created_at: string;
  updated_at?: UpdatedAt;
  leverage?: Leverage;
  reduce_only?: boolean;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId4;
  user_public_id?: UserPublicId2;
  plan_public_id?: PlanPublicId;
  paired_group_id?: PairedGroupId1;
  paired_group_size?: PairedGroupSize1;
  paired_group_index?: PairedGroupIndex1;
  paired_group_policy?: PairedGroupPolicy1;
}
export interface OrderEventData {
  type: Type25;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic26;
  exchange_order_id: string;
  client_order_id: string;
  exchange: Exchange6;
  instrument: string;
  event: Event1;
  reason?: Reason1;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId5;
  user_public_id?: UserPublicId3;
  paired_group_id?: PairedGroupId2;
  paired_group_size?: PairedGroupSize2;
  paired_group_index?: PairedGroupIndex2;
  paired_group_policy?: PairedGroupPolicy2;
}
export interface OrderReplaceData {
  type: Type26;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic27;
  exchange: Exchange7;
  instrument: string;
  exchange_order_id: string;
  client_order_id: string;
  new_quantity?: NewQuantity;
  new_price?: NewPrice;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId6;
  user_public_id?: UserPublicId4;
}
export interface OrderRequestData {
  type: Type27;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic28;
  strategy_id: string;
  exchange: Exchange8;
  instrument: string;
  mode: Mode3;
  side: Side2;
  order_type: OrderType1;
  quantity: number;
  price?: Price1;
  stop_price?: StopPrice;
  client_order_id: string;
  signaled_at?: SignaledAt;
  strategy_tag?: StrategyTag;
  leverage?: Leverage1;
  reduce_only?: boolean;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId7;
  user_public_id?: UserPublicId5;
  paired_group_id?: PairedGroupId3;
  paired_group_size?: PairedGroupSize3;
  paired_group_index?: PairedGroupIndex3;
  paired_group_policy?: PairedGroupPolicy3;
  origin?: Origin1;
  replay_window_start?: ReplayWindowStart1;
  replay_window_end?: ReplayWindowEnd1;
}
export interface PortfolioDriftEpisodeEventData {
  type: Type28;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic29;
  wallet_public_id: string;
  exchange: string;
  mode: Mode4;
  episode_public_id: string;
  lifecycle: Lifecycle;
  opened_at: string;
  closed_at?: ClosedAt;
  mismatch_count: number;
  resolution_reason?: ResolutionReason;
}
export interface PositionData {
  type: Type29;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic30;
  instrument: string;
  instrument_public_id?: string;
  exchange: Exchange9;
  mode?: Mode5;
  quantity: number;
  average_price?: AveragePrice1;
  unrealized_pnl?: UnrealizedPnl;
  realized_pnl: number;
  mark_price?: MarkPrice;
  marked_at?: MarkedAt;
  source_venue_event_id?: SourceVenueEventId;
  position_cycle_public_id?: PositionCyclePublicId1;
  wallet_public_id?: string;
}
export interface ProcessCommandAckData {
  type: Type30;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic31;
  command_id: string;
  coordinator: string;
  process_name: string;
  status: string;
  detail?: Detail;
  signature: string;
}
export interface ProcessCommandData {
  type: Type31;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic32;
  command_id: string;
  coordinator: string;
  process_name: string;
  action: string;
  issued_by: string;
  issued_at: string;
  signature: string;
}
export interface ProcessConfiguredEventData {
  type: Type32;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic33;
  process_names: ProcessNames;
  snapshot_at: string;
}
export interface ProcessRunEventData {
  type: Type33;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic34;
  process_name: string;
  run_id: string;
  status: string;
  started_at: string;
  completed_at?: CompletedAt;
  exit_code?: ExitCode;
}
export interface ProcessSummaryEventData {
  type: Type34;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic35;
  coordinator?: string;
  coordinator_label?: CoordinatorLabel;
  processes: Processes;
  snapshot_at: string;
}
export interface ProcessSummaryItem {
  name: string;
  running: boolean;
  enabled: boolean;
  role: string;
  lifecycle: string;
  active_public_id?: ActivePublicId;
  rss_bytes?: RssBytes;
  cpu_percent?: CpuPercent;
  owned?: boolean;
}
export interface RelatedInstrumentData {
  type: Type35;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic36;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  asset_type: string;
  relationship_type: string;
  contract_family: ContractFamily2;
  is_selected: boolean;
}
export interface ReplayEndData {
  type: Type36;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic37;
}
export interface ReplayStartData {
  type: Type37;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic38;
  started_at?: StartedAt;
}
export interface ScopeGrantedData {
  type: Type38;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic39;
  grant_public_id: string;
  operator_public_id: string;
  wallet_public_id: string;
  scope_kind: ScopeKind;
  underlying_public_id?: UnderlyingPublicId;
  instrument_public_id?: InstrumentPublicId;
  granted_at: string;
  granted_by_user_public_id: string;
  reason?: Reason2;
}
export interface ScopeHandedOverData {
  type: Type39;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic40;
  grant_public_id: string;
  from_operator_public_id: string;
  to_operator_public_id: string;
  wallet_public_id: string;
  scope_kind: ScopeKind1;
  underlying_public_id?: UnderlyingPublicId1;
  instrument_public_id?: InstrumentPublicId1;
  handover_at: string;
  handover_by_user_public_id: string;
  reason?: Reason3;
}
export interface ScopeRevokedData {
  type: Type40;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic41;
  grant_public_id: string;
  operator_public_id: string;
  wallet_public_id: string;
  scope_kind: ScopeKind2;
  underlying_public_id?: UnderlyingPublicId2;
  instrument_public_id?: InstrumentPublicId2;
  revoked_at: string;
  revoked_by_user_public_id?: RevokedByUserPublicId;
  reason?: Reason4;
}
export interface SettingChangedData {
  type: Type41;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic42;
  key: string;
  value: string;
  category: string;
  updated_by?: UpdatedBy;
}
export interface SignalData {
  type: Type42;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic43;
  instrument: string;
  exchange: Exchange10;
  side: Side3;
  strength: number;
  reason: string;
  price?: Price2;
  strategy_name?: StrategyName;
  fired_at: string;
  wallet_public_id?: string;
  operator_public_id?: OperatorPublicId8;
  user_public_id?: UserPublicId6;
  ai_review_public_id?: AiReviewPublicId;
  ai_review_dispatch_version?: AiReviewDispatchVersion;
  paired_group_id?: PairedGroupId4;
  paired_group_size?: PairedGroupSize4;
  paired_group_index?: PairedGroupIndex4;
  paired_group_policy?: PairedGroupPolicy4;
  paired_group_key?: PairedGroupKey;
  origin?: Origin2;
  replay_window_start?: ReplayWindowStart2;
  replay_window_end?: ReplayWindowEnd2;
}
export interface StrategyListEventData {
  type: Type43;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic44;
  strategy_classes: StrategyClasses;
  snapshot_at: string;
}
export interface SymbolAliasUpdateData {
  type: Type44;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic45;
  event: Event2;
  action: Action;
}
export interface TickData {
  type: Type45;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic46;
  instrument: string;
  exchange: Exchange11;
  volume: number;
  bid?: Bid;
  ask?: Ask;
  last?: Last;
  is_delayed?: boolean;
  is_extended_hours?: IsExtendedHours;
  origin?: Origin3;
  replay_window_start?: ReplayWindowStart3;
  replay_window_end?: ReplayWindowEnd3;
}
export interface TradeData {
  type: Type46;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic47;
  instrument: string;
  exchange: Exchange12;
  executed_at?: ExecutedAt;
  price: number;
  volume: number;
  side?: Side4;
  trade_id?: TradeId1;
  origin?: Origin4;
  replay_window_start?: ReplayWindowStart4;
  replay_window_end?: ReplayWindowEnd4;
}
export interface UnderlyingAssetData {
  type: Type47;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic48;
  ticker: string;
  name: string;
  asset_class: string;
  sector: Sector;
  description: Description;
  instrument_count: number;
}
export interface UnderlyingInstrumentData {
  type: Type48;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic49;
  instrument_public_id: string;
  native_symbol: string;
  exchange: string;
  asset_type: string;
  relationship_type: string;
  contract_family: ContractFamily3;
}
export interface UserDeactivatedData {
  type: Type49;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic50;
  user_public_id: string;
  deactivated_at: string;
  reason?: Reason5;
}
export interface VenueFeeScheduleData {
  type: Type50;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic51;
  exchange: string;
  instrument_public_id: InstrumentPublicId3;
  fee_tier: string;
  maker_bps: number;
  taker_bps: number;
  min_volume_30d: MinVolume30D;
  currency: string;
}
export interface WSAuthCompleteResponse {
  type: Type51;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic52;
  available_topics: AvailableTopics;
  user_role: UserRole;
  session_expires_at?: SessionExpiresAt;
  ws_token_exp: string;
}
export interface WSAuthExpiredResponse {
  type: Type52;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic53;
}
export interface WSAuthFailedResponse {
  type: Type53;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic54;
  reason?: Reason6;
}
export interface WSAuthOkResponse {
  type: Type54;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic55;
  exp: string;
}
export interface WSAuthRequiredResponse {
  type: Type55;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic56;
  timeout?: number;
}
export interface WSAuthenticateRequest {
  type: Type56;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic57;
  ws_token: string;
}
export interface WSErrorResponse {
  type: Type57;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic58;
  message: string;
}
export interface WSGetSubscriptionsRequest {
  type: Type58;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic59;
}
export interface WSPingRequest {
  type: Type59;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic60;
}
export interface WSPongResponse {
  type: Type60;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic61;
  active_connections: number;
}
export interface WSReauthOkResponse {
  type: Type61;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic62;
  exp: string;
}
export interface WSReauthRequest {
  type: Type62;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic63;
  ws_token: string;
}
export interface WSReauthRequiredResponse {
  type: Type63;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic64;
  deadline: string;
}
export interface WSSubscribeRequest {
  type: Type64;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic65;
  topics: Topics;
}
export interface WSSubscriptionSuccessResponse {
  type: Type65;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic66;
  action: Action1;
  status: Status2;
  topics: Topics1;
  denied_topics?: DeniedTopics;
  active_subscriptions: ActiveSubscriptions;
  message?: Message;
}
export interface WSSubscriptionsListResponse {
  type: Type66;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic67;
  subscriptions: Subscriptions;
  available_topics: AvailableTopics1;
  total_available: number;
}
export interface WSUnsubscribeRequest {
  type: Type67;
  sequence_id: number;
  public_id: string;
  timestamp: string;
  session_id: string;
  topic?: Topic68;
  topics: Topics2;
}
