/**
 * Local-vendored SVG image with deterministic textual-badge fallback.
 *
 * Used by `SingleAssetIcon` and `PairIcon` to render crypto/flag icons.
 * Icons are vendored under `public/icons/{crypto,flags}/` so the trading
 * UI works in air-gapped environments and is not coupled to any
 * third-party CDN. See `public/icons/LICENSE.md` for upstream attribution
 * (CC0 cryptocurrency-icons + MIT circle-flags).
 *
 * Fallback strategy: a generated manifest (`iconManifest.generated.ts`,
 * regenerated by `pnpm icons:vendor`) lists exactly which symbols are
 * vendored locally. The `<RemoteSvg>` component consults the manifest
 * before rendering an `<img>`. If the symbol is absent, it skips the
 * image path entirely and renders a textual badge with the uppercased
 * ticker. This is more robust than relying on the browser's `error`
 * event because Vite's SPA dev server returns `index.html` (HTTP 200)
 * for missing static assets — `<img>` would silently load HTML instead
 * of triggering `onerror`. We still keep an `onError` handler as a
 * belt-and-suspenders safety net for misconfigured production hosts.
 *
 * To add new tokens or country codes:
 *   1. Add the entry to `registry/crypto.ts` or `registry/fiat.ts`
 *   2. Run `pnpm icons:vendor` to sync from upstream + refresh manifest
 *   3. Commit the new SVG files + regenerated manifest
 */
import { CSSProperties, useState } from 'react'

type RemoteSvgProps = {
  src: string
  label: string
  size: number
  shape?: 'circle' | 'rect'
  fallbackBackground?: string
  vendored?: boolean
}

export function RemoteSvg({
  src,
  label,
  size,
  shape = 'circle',
  fallbackBackground = 'rgba(255,255,255,0.06)',
  vendored = true,
}: Readonly<RemoteSvgProps>): React.ReactElement {
  const [errored, setErrored] = useState(false)

  if (errored || !vendored) {
    const fallbackStyle: CSSProperties = {
      width: size,
      height: size,
      borderRadius: shape === 'circle' ? '50%' : 4,
      background: fallbackBackground,
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: Math.max(8, Math.round(size / 3.2)),
      fontWeight: 600,
      color: '#888',
      flexShrink: 0,
    }

    return (
      <span style={fallbackStyle} aria-label={label} role='img'>
        {label.slice(0, 3)}
      </span>
    )
  }

  return (
    <img
      src={src}
      alt={label}
      width={size}
      height={size}
      onError={() => setErrored(true)}
      loading='lazy'
      decoding='async'
      style={{
        borderRadius: shape === 'circle' ? '50%' : 4,
        display: 'block',
        objectFit: 'cover',
        flexShrink: 0,
      }}
    />
  )
}
