import type { CryptoIconSpec } from '../types'

const cryptoIcon = (symbol: string): CryptoIconSpec => ({ kind: 'crypto', symbol })

export const CRYPTO_ICONS: Record<string, CryptoIconSpec> = {
  BTC: cryptoIcon('btc'),
  ETH: cryptoIcon('eth'),
  USDT: cryptoIcon('usdt'),
  USDC: cryptoIcon('usdc'),
  DAI: cryptoIcon('dai'),
  PYUSD: cryptoIcon('pyusd'),
  RLUSD: cryptoIcon('rlusd'),
  SOL: cryptoIcon('sol'),
  XRP: cryptoIcon('xrp'),
  DOGE: cryptoIcon('doge'),
  LTC: cryptoIcon('ltc'),
  LINK: cryptoIcon('link'),
  DOT: cryptoIcon('dot'),
  ADA: cryptoIcon('ada'),
  AVAX: cryptoIcon('avax'),
  UNI: cryptoIcon('uni'),
  AAVE: cryptoIcon('aave'),
  ATOM: cryptoIcon('atom'),
  NEAR: cryptoIcon('near'),
  ALGO: cryptoIcon('algo'),
  FIL: cryptoIcon('fil'),
  XLM: cryptoIcon('xlm'),
  TRX: cryptoIcon('trx'),
  ETC: cryptoIcon('etc'),
  APE: cryptoIcon('ape'),
  SHIB: cryptoIcon('shib'),
  RENDER: cryptoIcon('render'),
  TAO: cryptoIcon('tao'),
  ZEC: cryptoIcon('zec'),
  ONDO: cryptoIcon('ondo'),
  TIA: cryptoIcon('tia'),
  INJ: cryptoIcon('inj'),
  OP: cryptoIcon('op'),
  ARB: cryptoIcon('arb'),
  SUI: cryptoIcon('sui'),
  XMR: cryptoIcon('xmr'),
  MATIC: cryptoIcon('matic'),
  POL: cryptoIcon('pol'),
  HYPE: cryptoIcon('hype'),
  PEPE: cryptoIcon('pepe'),
  BNB: cryptoIcon('bnb'),
  BCH: cryptoIcon('bch'),
}
