#!/usr/bin/env bash
#
# vendor-icons.sh — re-sync `public/icons/` from upstream OSS crypto + flag
# repos. Run after adding new entries to
# `src/components/InstrumentIcon/registry/crypto.ts` or
# `src/components/InstrumentIcon/registry/fiat.ts`.
#
# Required tools: git, awk, sort, uniq.
# Output: SVGs copied into public/icons/{crypto,flags}/ (relative to repo
# root).
# Idempotent: re-runs overwrite existing files with current upstream.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PUBLIC_ICONS="$REPO_ROOT/public/icons"
TMP_DIR="$(mktemp -d -t snapper-icons-XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

CRYPTO_REPO="https://github.com/spothq/cryptocurrency-icons.git"
FLAGS_REPO="https://github.com/HatScripts/circle-flags.git"

echo "Cloning upstream repos to $TMP_DIR ..."
git clone --depth 1 --quiet "$CRYPTO_REPO" "$TMP_DIR/crypto-src"
git clone --depth 1 --quiet "$FLAGS_REPO" "$TMP_DIR/flags-src"

echo "Extracting required tokens from registry/crypto.ts ..."
CRYPTOS="$TMP_DIR/cryptos.txt"
awk -F"'" '/cryptoIcon\(/{print $2}' \
  "$REPO_ROOT/src/components/InstrumentIcon/registry/crypto.ts" \
  | sort -u > "$CRYPTOS"

echo "Extracting required country codes from registry/fiat.ts ..."
FLAGS="$TMP_DIR/flags.txt"
awk -F"'" '/flag\(/{print $2}' \
  "$REPO_ROOT/src/components/InstrumentIcon/registry/fiat.ts" \
  | sort -u > "$FLAGS"

mkdir -p "$PUBLIC_ICONS/crypto" "$PUBLIC_ICONS/flags"

crypto_copied=0
crypto_missing=()
while read -r sym; do
  src="$TMP_DIR/crypto-src/svg/color/${sym}.svg"
  if [ -f "$src" ]; then
    cp "$src" "$PUBLIC_ICONS/crypto/${sym}.svg"
    crypto_copied=$((crypto_copied + 1))
  else
    crypto_missing+=("$sym")
  fi
done < "$CRYPTOS"

flag_copied=0
flag_missing=()
while read -r cc; do
  src="$TMP_DIR/flags-src/flags/${cc}.svg"
  if [ -f "$src" ]; then
    cp "$src" "$PUBLIC_ICONS/flags/${cc}.svg"
    flag_copied=$((flag_copied + 1))
  else
    flag_missing+=("$cc")
  fi
done < "$FLAGS"

echo ""
echo "Vendor sync complete:"
echo "  crypto: $crypto_copied SVGs copied"
if [ ${#crypto_missing[@]} -gt 0 ]; then
  echo "  crypto MISSING from upstream (will use textual fallback): ${crypto_missing[*]}"
fi
echo "  flags : $flag_copied SVGs copied"
if [ ${#flag_missing[@]} -gt 0 ]; then
  echo "  flags MISSING from upstream: ${flag_missing[*]}"
fi

# Generate the vendored-asset manifest. RemoteSvg.tsx consumes it to skip
# the <img> path entirely for symbols not present locally — keeps the
# textual fallback deterministic instead of relying on browser onError
# (which Vite's SPA-fallback handler defeats by returning index.html with
# HTTP 200 for missing static assets in dev mode).
MANIFEST="$REPO_ROOT/src/components/InstrumentIcon/iconManifest.generated.ts"
{
  echo "// AUTO-GENERATED by scripts/vendor-icons.sh — do not edit by hand."
  echo "// Re-run 'pnpm icons:vendor' to regenerate after adding registry entries."
  echo ""
  echo "export const VENDORED_CRYPTO_ICONS: ReadonlySet<string> = new Set(["
  ls "$PUBLIC_ICONS/crypto" | sed -E "s/\.svg$//" | sort | sed -E "s/^/  '/" | sed -E "s/$/',/"
  echo "])"
  echo ""
  echo "export const VENDORED_FLAG_ICONS: ReadonlySet<string> = new Set(["
  ls "$PUBLIC_ICONS/flags" | sed -E "s/\.svg$//" | sort | sed -E "s/^/  '/" | sed -E "s/$/',/"
  echo "])"
} > "$MANIFEST"

echo "Generated manifest: $MANIFEST"
